[package]
name = "gravity_clustering"
version = "0.1.0"
authors = ["boris"]

[dependencies]
ndarray = "0.12.1"
# ndarray-linalg = { version = "0.10", features = ["openblas"] }
# ndarray-linalg = "0.10"
rand = "0.5.5"
num_cpus = "1.8.0"
rayon = "1.0.2"
